GET http://localhost:3000/users

###


POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "x",
    "passwd": "x",
    "email": "x",
    "phoneNumber": "x",
    "age": "x",
    "sport": "x"
}

###


POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "lorppi",
    "passwd": "sipuli609"
}