GET http://localhost:3000/users

###


POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "tester",
    "passwd": "mamba",
    "email": "mamba@tester.com",
    "phoneNumber": "0405091111",
    "age": "21",
    "sport": "football"
}

###


POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "tester",
    "passwd": "mamba"
}