GET http://localhost:3000/users

###


POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "jaa",
    "passwd": "jeaa",
    "email": "mamba@tefa.afa",
    "phoneNumber": "040509332",
    "age": "21",
    "sport": "football"
}

###


POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "tester",
    "passwd": "mamba"
}